<a href="https://colab.research.google.com/github/Yashcode007/masters_in_ai/blob/deep_learning_wb_84520/dilation_and_upcovolution_5_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

In [6]:
net = torch.nn.Conv2d(1,1,3,2,1)
x = torch.zeros(1,1,5,5)
print(x.shape, net(x).shape)

torch.Size([1, 1, 5, 5]) torch.Size([1, 1, 3, 3])


In [7]:
print(x)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])


In [8]:
net(x)

tensor([[[[0.2182, 0.2182, 0.2182],
          [0.2182, 0.2182, 0.2182],
          [0.2182, 0.2182, 0.2182]]]], grad_fn=<ConvolutionBackward0>)

In [11]:
net1 = torch.nn.Sequential(
    torch.nn.Conv2d(1,1,3,stride=2,padding=1,dilation=1),
    torch.nn.ReLU(),
    torch.nn.Conv2d(1,1,3,stride=1,padding=1,dilation=1)
)

net2 = torch.nn.Sequential(
    torch.nn.Conv2d(1,1,3,stride=1,padding=1,dilation=1),
    torch.nn.ReLU(),
    torch.nn.Conv2d(1,1,3,stride=1,padding=2,dilation=2),
)

In [13]:
x = torch.zeros(1,1,32,32)
print(x.shape, net1(x).shape)
print(x.shape, net2(x).shape)

torch.Size([1, 1, 32, 32]) torch.Size([1, 1, 16, 16])
torch.Size([1, 1, 32, 32]) torch.Size([1, 1, 32, 32])


In [14]:
y1 = net1(x)
y2 = net2(x)
print(y1)
print(y2)

tensor([[[[-0.2402, -0.2448, -0.2448, -0.2448, -0.2448, -0.2448, -0.2448,
           -0.2448, -0.2448, -0.2448, -0.2448, -0.2448, -0.2448, -0.2448,
           -0.2448, -0.2555],
          [-0.2145, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256,
           -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256,
           -0.2256, -0.2338],
          [-0.2145, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256,
           -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256,
           -0.2256, -0.2338],
          [-0.2145, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256,
           -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256,
           -0.2256, -0.2338],
          [-0.2145, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256,
           -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256,
           -0.2256, -0.2338],
          [-0.2145, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256, -0.2256,
           -0.2256, -0.2256, -0.2256

In [15]:
net1 = torch.nn.Sequential(
    torch.nn.Conv2d(1,1,3,stride=2,padding=1,dilation=1),
    torch.nn.ReLU(),
    torch.nn.Conv2d(1,1,3,stride=1,padding=1,dilation=1),
    torch.nn.ReLU(),
    torch.nn.ConvTranspose2d(1,1,3,stride=2,padding=1,output_padding=1)
)

x = torch.randn(1,1,6,6)
print(net1(x).shape)

torch.Size([1, 1, 6, 6])
