<a href="https://colab.research.google.com/github/Yashcode007/masters_in_ai/blob/deep_learning_wb_84520/distribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Lectur 1.3 -> Distribution and Sampling in Pytorch**

In [2]:
import torch
import torch.distributions as dist

In [9]:
#Lets create a Bernoulli Distribution

bernoulli = dist.Bernoulli(torch.tensor([0.5]))
print(bernoulli)

#Sample from the distribution
for _ in range(10):
  print(bernoulli.sample())

Bernoulli(probs: tensor([0.5000]))
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([1.])


In [11]:
samples = [bernoulli.sample() for _ in range(1000)]
print(f"Mean:{torch.mean(torch.stack(samples))}")
print(f"Variance:{torch.var(torch.stack(samples))}")

Mean:0.4880000054836273
Variance:0.2501060962677002


We run it multiple time , the mean is sometimes -0.49 , 0.42, 0.52 , etc

But it is rarely 0.5

In [13]:
# Lets create a normal distribution
# 0.0-> centered at mean , 1.0 -> standard deviation of 1
normal = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0]))

for _ in range(10):
  print(normal.sample())

tensor([1.5304])
tensor([-1.0506])
tensor([-0.4628])
tensor([-0.3418])
tensor([1.7925])
tensor([-0.8257])
tensor([-0.7269])
tensor([0.5684])
tensor([-0.4867])
tensor([0.8032])


In [14]:
samples = [normal.sample() for _ in range(1000)]
print(f"Mean:{torch.mean(torch.stack(samples))}")
print(f"Variance:{torch.var(torch.stack(samples))}")

Mean:-0.007820331491529942
Variance:1.0673729181289673
