<a href="https://colab.research.google.com/github/Yashcode007/masters_in_ai/blob/deep_learning_wb_84520/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
a = torch.tensor([1.0,2,3], dtype=torch.float32)
print(a.dtype)

torch.float32


In [3]:
print(a)

tensor([1., 2., 3.])


In [4]:
b = torch.zeros([3,2,2], dtype=torch.float32)
print(b)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [5]:
a = torch.arange(10)
b = torch.ones(10)
print(f'a => {a}')
print(f'b => {b}')

a => tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b => tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [6]:
print(a+b)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [7]:
a_gpu = a.to('cuda')
b_gpu = b.to('cuda')
%timeit c_gpu = a_gpu+b_gpu

12.3 µs ± 5.51 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
a = torch.arange(6)
print(a.reshape(2,3))

tensor([[0, 1, 2],
        [3, 4, 5]])


In [12]:
a = torch.rand(2,3)
print(a)
print(a.mT)    # Matrix Transpose Function

tensor([[0.3307, 0.5835, 0.2519],
        [0.4797, 0.5813, 0.3486]])
tensor([[0.3307, 0.4797],
        [0.5835, 0.5813],
        [0.2519, 0.3486]])


In [13]:
a = torch.arange(6)
print(a)

tensor([0, 1, 2, 3, 4, 5])


In [15]:
x = torch.randn(10,2)
d = torch.zeros(10,10)
for i in range(10):
  for j in range(10):
    d[i,j] = (x[i]-x[j]).pow(2).sum()
print(d)

tensor([[ 0.0000,  4.4225,  0.7277,  1.3832,  5.3419, 12.6440,  2.5745,  0.6472,
          1.3888,  4.6543],
        [ 4.4225,  0.0000,  2.0105,  2.5330,  1.2263,  5.8772,  1.4466,  6.8482,
          0.8570,  8.9873],
        [ 0.7277,  2.0105,  0.0000,  1.6773,  3.9512,  7.4518,  0.5784,  1.4411,
          0.3874,  3.5691],
        [ 1.3832,  2.5330,  1.6773,  0.0000,  1.6171, 14.0486,  3.5138,  3.8954,
          0.8758,  9.8094],
        [ 5.3419,  1.2263,  3.9512,  1.6171,  0.0000, 12.3988,  4.5756,  9.2184,
          1.8693, 14.6773],
        [12.6440,  5.8772,  7.4518, 14.0486, 12.3988,  0.0000,  3.8903, 12.3119,
          7.9341,  7.0055],
        [ 2.5745,  1.4466,  0.5784,  3.5138,  4.5756,  3.8903,  0.0000,  3.0885,
          0.9196,  3.2347],
        [ 0.6472,  6.8482,  1.4411,  3.8954,  9.2184, 12.3119,  3.0885,  0.0000,
          3.0811,  2.3668],
        [ 1.3888,  0.8570,  0.3874,  0.8758,  1.8693,  7.9341,  0.9196,  3.0811,
          0.0000,  6.1472],
        [ 4.6543,  